site_name: Introduction to Arduino Documentation

plugins:
  - glightbox
  - search
  - awesome-pages



extra_css:
  - css/styles.css  # Path relative to the docs/ directory
  - css/highlights.css
  - css/tablesAndFigures.css
  - https://unpkg.com/katex@0/dist/katex.min.css


markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - md_in_html
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - ./includes/abbreviations.md

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

watch:
  - includes

theme: 
  name: material
  features:
  - content.tooltips
  - content.code.copy
  - content.code.select
  - content.code.annotate
  - navigation.indexes
  
  palette: 
  #Light Mode
  - scheme: default
    toggle: 
      icon: material/weather-night
      name: Dark Mode
    primary: blue
    accent: deep orange

  #Dark Mode
  - scheme: slate
    toggle: 
      icon: material/weather-sunny
      name: Light Mode
    primary: green
    accent: deep purple


  
